# Generated by Django 4.2.6 on 2023-10-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='phone',
        ),
    ]
