# Generated by Django 4.2.6 on 2023-10-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='location.address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
