# Generated by Django 4.2.6 on 2023-10-07 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_send',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
